//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winCompuertaGP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIntegracionesVentas
    {
        public int ID { get; set; }
        public short TIPODOCARN { get; set; }
        public string NUMDOCARN { get; set; }
        public Nullable<short> TIPODOCGP { get; set; }
        public string NUMDOCGP { get; set; }
        public string DOCSTATUS { get; set; }
        public string IDCLIENTE { get; set; }
        public System.DateTime FECHADOC { get; set; }
        public string OBSERVACIONES { get; set; }
        public short ESACTUAL { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHAHORA { get; set; }
        public string MENSAJE { get; set; }
        public string MENSAJELARGO { get; set; }
        public string DOCID_GP { get; set; }
        public Nullable<short> SOPTYPE_GP { get; set; }
    }
}
